### ISSUE TITLE
Don't fail with when reading an empty connected-realms file

### ISSUE THREAD

**Issue by ptarjan** [ff14-advanced-market-search/mega-alerts#47]
I'm following the initial setup instructions and it fails on startup. Either there is a missing required environment variable or some other required setup. My env file looks like:

```
$ cat mega-alerts.env
MEGA_WEBHOOK_URL=https://discord.com/api/webhooks/<redacted>
WOW_CLIENT_ID=<redacted>
WOW_CLIENT_SECRET=<redacted>
WOW_REGION=US
DESIRED_PETS={"2475":10000}
```

```
 $ docker run -it --env-file mega-alerts.env cohenaj194/mega-alerts:latest
Sleep 10 sec on start to avoid spamming the api
Optional variable MEGA_THREADS not found in env or mega_data.json
Optional variable SCAN_TIME_MIN not found in env or mega_data.json
Optional variable SCAN_TIME_MAX not found in env or mega_data.json
Optional variable REFRESH_ALERTS not found in env or mega_data.json
loading WOW_CLIENT_ID from environment variables
loading WOW_CLIENT_SECRET from environment variables
loading MEGA_WEBHOOK_URL from environment variables
Optional variable WOWHEAD_LINK not found in env or mega_data.json
Optional variable SHOW_BID_PRICES not found in env or mega_data.json
loading WOW_REGION from environment variables
Optional variable EXTRA_ALERTS not found in env or mega_data.json
Traceback (most recent call last):
  File "mega-alerts.py", line 18, in <module>
    mega_data = utils.mega_data_setup.MegaData()
  File "/app/utils/mega_data_setup.py", line 32, in __init__
    open(f"data/{str(self.REGION).lower()}-wow-connected-realm-ids.json")
FileNotFoundError: [Errno 2] No such file or directory: 'data/us-wow-connected-realm-ids.json'
```

**Comment by ptarjan** [comment]
I was saying that if I set the region to an invalid value the error isn’t
very obvious.
